spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lotericas
    username: lotericas
    password: lotericas
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
